create table if not exists public.wedding_rsvps (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  starter text not null,
  sorbet text not null default '',
  main_course text not null,
  dessert text not null,
  notes text not null default '',
  dependent_of text,
  "isKid" boolean not null default false,
  submitted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.wedding_rsvps enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.wedding_rsvps to anon, authenticated;
grant usage, select on sequence public.wedding_rsvps_id_seq to anon, authenticated;

drop policy if exists "Allow anon and authenticated insert" on public.wedding_rsvps;
create policy "Allow anon and authenticated insert"
on public.wedding_rsvps
for insert
to anon, authenticated
with check (true);
